# Generated by Django 4.2 on 2023-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField()),
                ('base_link', models.URLField(max_length=1024)),
                ('user_name', models.CharField(max_length=256)),
            ],
        ),
    ]
