# Generated by Django 4.2 on 2023-04-29 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_alter_subscription_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('port', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='base_link',
            new_name='base_link1',
        ),
        migrations.AddField(
            model_name='subscription',
            name='base_link2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='base_link3',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
