# Generated by Django 4.2 on 2023-04-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_middleserver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expire_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='traffic',
            field=models.IntegerField(default=0, help_text='In gigabytes'),
        ),
    ]
