# Generated by Django 4.2 on 2023-04-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_subscription_created_subscription_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleserver',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
