# Generated by Django 4.2 on 2023-05-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_subscription_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(blank=True, max_length=128, null=True)),
                ('host', models.CharField(blank=True, max_length=128, null=True)),
                ('auth', models.CharField(blank=True, max_length=512, null=True)),
                ('panel', models.CharField(choices=[('XUI', 'XUI'), ('Marzban', 'Marzban')], default='Marzban', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(blank=True, help_text='for xui links', max_length=256, null=True)),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('URI', 'URI'), ('Subscription_Link', 'Subscription_Link'), ('Encoded', 'Encoded'), ('Clash', 'Clash')], default='Subscription_Link', max_length=64)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.server')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscription')),
            ],
        ),
    ]
