# Generated by Django 4.2 on 2023-05-09 23:47

from django.db import migrations


def convert_links(apps, schema_editor):
    Subscription = apps.get_model("subscribe", "Subscription")
    Server = apps.get_model("subscribe", "Server")
    Link = apps.get_model("subscribe", "Link")
    s = Server.objects.create()
    for row in Subscription.objects.all():
        l = Link.objects.create(value=row.base_link1, server=s, subscription=row)

class Migration(migrations.Migration):
    dependencies = [
        ('subscribe', '0007_server_alter_subscription_expire_date_link'),
    ]

    operations = [
        migrations.RunPython(convert_links, reverse_code=migrations.RunPython.noop)
    ]