# Generated by Django 4.2 on 2023-05-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_auto_20230509_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.CharField(default=54321, max_length=16),
        ),
    ]
