# Generated by Django 4.2 on 2023-05-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0010_remove_subscription_base_link1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='panel_add',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Time Expired', 'Time Expired'), ('Traffic Expired', 'Traffic Expired'), ('Disabled', 'Disabled')], default='Active', max_length=32),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('URI', 'URI'), ('Subscription_Link', 'Subscription_Link'), ('Encoded', 'Encoded'), ('Clash', 'Clash'), ('URI_List', 'URI_List')], default='Subscription_Link', max_length=64),
        ),
        migrations.AlterField(
            model_name='server',
            name='panel',
            field=models.CharField(choices=[('XUI', 'XUI'), ('Marzban', 'Marzban'), ('XUI 3', 'XUI 3')], default='Marzban', max_length=16),
        ),
    ]
