# Generated by Django 4.2 on 2023-05-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0012_fastsubscription_subscription_last_used_traffic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
