# Generated by Django 4.2 on 2023-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0014_link_include_original_middleserver_server_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleserver',
            name='remark',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='middleserver',
            name='trojan_extra_config',
            field=models.JSONField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='middleserver',
            name='vless_extra_config',
            field=models.JSONField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='middleserver',
            name='vmess_extra_config',
            field=models.JSONField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='remark',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
