# Generated by Django 4.2 on 2023-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0015_middleserver_remark_middleserver_trojan_extra_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pre_used_traffic',
            field=models.IntegerField(default=0, help_text='Used traffic that is not included in panels or a traffic volume that the corresponding config is deleted'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_used_traffic',
            field=models.IntegerField(default=0, help_text='The traffic used by user of current configs (pre used traffic is not included) and will be updated everytime user requests or action call in admin page'),
        ),
    ]
