# Generated by Django 4.2 on 2023-08-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0016_subscription_pre_used_traffic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
