# Generated by Django 4.2 on 2023-09-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0017_subscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='used_traffic',
            field=models.FloatField(default=0, help_text='In gigabytes'),
        ),
    ]
