# Generated by Django 4.2 on 2023-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0018_link_used_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleserver',
            name='apply_on',
            field=models.TextField(blank=True, null=True),
        ),
    ]
