# Generated by Django 4.2 on 2023-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0019_middleserver_apply_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='end_remark',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
